POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY5OTA3OWNjMDYxNzA4MmM3MTkwN2JmNCIsImlhdCI6MTc3MTE1Nzc0MCwiZXhwIjoxNzcxMTYxMzQwfQ.gxLWPOixEnbRXeYwtYUSElkyhPpSnfzO9CWbp4x0hIA

{
    "title": "test-create",
    "author": "test",
    "url": "http://example.com/test-create"
}