POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY5OTA3OWNjMDYxNzA4MmM3MTkwN2JmNCIsImlhdCI6MTc3MTA4MzkwOSwiZXhwIjoxNzcxMDg3NTA5fQ.X_weDAyPXaFQ6gSiB-5dcdLirD7sbvmsSi4AtRWzeBM

{
  "title": "test-user-extractor-1",
  "author": "John Doe",
  "url": "http://example.com/test-user-extractor",
  "likes": 0
}